name: "crawler-website-cd"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  cd:
    name: Connect SSH to server and deploy
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Tags docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: takashilouisnguyen/crawler-website
          tags: |
            type=raw, value={{date 'YYYY-MM-DD'}}

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIV_KEY }}
          port: 22
          script: |
            docker rm -f website &2>/dev/null || true
            docker images -- format '{{.Repository}}:{{.Tag}}' | grep 'takashilouisnguyen/crawler-website' | xargs -r docker rmi -f
            docker run --net crawler -d --name website -p 3100:80 ${{ steps.meta.outputs.tags }}
          continue-on-error: true